"""Freeze the core corpus expectations into ``contracts/core/fixtures/expected.json``.

The compat expectations live in ``contracts/fixtures/expected-hashes.json`` and are
produced by ``contracts_freeze.py``. Core needs its own file for a different reason than
"the corpus moved": a digest that Python computes at load time proves nothing to Java.
Freezing it is what turns two implementations into evidence - Java recomputes the same
bytes from the same fixture and compares, so the two languages agree on *values*, not just
on shapes.

Every value here is recomputed from the corpus, so this file cannot disagree with the
implementation silently: ``--check`` rebuilds it and fails if the bytes on disk differ.
"""

from __future__ import annotations

import base64
import json
import sys

from resolveflow.contracts._schemaio import REPO_ROOT
from resolveflow.contracts.canonical import canonicalize
from resolveflow.contracts.core_corpus import (
    CORE_EXPECTED_PATH,
    SIGNING_KEY_ID,
    computed_placeholder_values,
    core_signing_keys,
    load_core_corpus,
    resolve_core_instance,
    strip_annotations,
    validate_core_corpus,
    validate_core_invalid_payloads,
    validate_core_reject_corpus,
)
from resolveflow.contracts.events import CORE_SIGNABLE_KEYS, core_signing_input_bytes

#: The corpus stores its signing key in ``valid.json``; the two members holding the seed
#: and the public key are read there rather than duplicated here.


def core_document() -> tuple[dict[str, object], list[str]]:
    """The frozen core expectations plus the validation lines printed while building them."""
    from cryptography.hazmat.primitives import serialization

    corpus = load_core_corpus()
    print_lines = validate_core_corpus(corpus)
    refused = validate_core_reject_corpus() + validate_core_invalid_payloads()
    print_lines.extend(refused)

    values = computed_placeholder_values(corpus)
    private_key, declared_public_key = core_signing_keys(corpus)

    payload_hashes: dict[str, str] = {}
    signatures: dict[str, str] = {}
    signing_inputs: dict[str, str] = {}
    canonical_payloads: dict[str, str] = {}

    # The token is read from the corpus and the value from the computed table, so the two
    # cannot agree by construction: a wrong token would raise instead of freezing itself.
    for name in sorted(key for key in corpus["components"] if not key.startswith("_")):
        component = corpus["components"][name]
        if "action" not in component:
            continue
        payload_hashes[name] = values[component["payload_hash"]]
        canonical_payloads[name] = canonicalize(
            {key: value for key, value in strip_annotations(component).items() if key != "payload_hash"}
        )

    for name in sorted(key for key in corpus["message_envelopes"] if not key.startswith("_")):
        signatures[name] = values[corpus["message_envelopes"][name]["signature"]]
        resolved = resolve_core_instance(corpus, "message_envelopes", name, values)
        unsigned = {key: value for key, value in resolved.items() if key != "signature"}
        signing_inputs[name] = core_signing_input_bytes(unsigned).decode("utf-8")

    document: dict[str, object] = {
        "_comment": [
            "Frozen core-v1.2 expectations. Generated by scripts/contracts_core_freeze.py; do not hand-edit.",
            "docs/core-contracts.md:17 fixes the payload hash and the signature input; docs/core-contracts.md:18 lists the 12 hashed fields; docs/core-contracts.md:19 keeps the version inside the result payload and signs topic.",
            "Java (com.resolveflow.shared.core) and Python (resolveflow.contracts.core_corpus) each reproduce these values from contracts/core/fixtures/valid.json. Either side failing means the two implementations disagree about the core wire.",
            "The signing key is the public RFC 8032 section 7.1 TEST 1 vector. It exists so the frozen signature can be verified in CI and is not a deployment key.",
            "signing_inputs records the exact bytes the signature covers, which is what makes the normalisation rule comparable across languages.",
        ],
        "algorithm": {
            "payload_hash": "SHA-256 over RFC 8785 canonical JSON of the 12 fields in docs/core-contracts.md:18",
            "event_signature": "Ed25519 (RFC 8032) over the canonical envelope excluding `signature` (docs/core-contracts.md:19)",
        },
        "signing_keys": {
            "key_id": SIGNING_KEY_ID,
            "private_seed_hex": corpus["signing_keys"][SIGNING_KEY_ID]["private_seed_hex"],
            "public_key_hex": corpus["signing_keys"][SIGNING_KEY_ID]["public_key_hex"],
            "private_key_pkcs8_base64": base64.b64encode(
                private_key.private_bytes(
                    encoding=serialization.Encoding.DER,
                    format=serialization.PrivateFormat.PKCS8,
                    encryption_algorithm=serialization.NoEncryption(),
                )
            ).decode("ascii"),
            "public_key_spki_base64": base64.b64encode(
                declared_public_key.public_bytes(
                    encoding=serialization.Encoding.DER,
                    format=serialization.PublicFormat.SubjectPublicKeyInfo,
                )
            ).decode("ascii"),
            "signed_members": list(CORE_SIGNABLE_KEYS),
        },
        "canonical_payloads": canonical_payloads,
        "payload_hashes": payload_hashes,
        "signing_inputs": signing_inputs,
        "event_signatures": signatures,
        "placeholder_values": values,
        "refused": refused,
    }
    return document, print_lines


def render(document: dict[str, object]) -> str:
    return json.dumps(document, ensure_ascii=False, indent=2) + "\n"


def main(argv: list[str]) -> int:
    check_only = "--check" in argv[1:]
    unexpected = [arg for arg in argv[1:] if arg != "--check"]
    if unexpected:
        print(f"unknown argument(s): {' '.join(unexpected)}", file=sys.stderr)
        return 64

    try:
        document, lines = core_document()
    except Exception as error:  # noqa: BLE001 - the CLI reports any corpus failure the same way
        print(f"core corpus is not usable: {error}", file=sys.stderr)
        return 1

    for line in lines:
        print(line)
    text = render(document)
    path = REPO_ROOT / CORE_EXPECTED_PATH
    if check_only:
        if not path.exists():
            print(f"{CORE_EXPECTED_PATH}: missing", file=sys.stderr)
            return 1
        with open(path, encoding="utf-8", newline="") as handle:
            on_disk = handle.read()
        if on_disk != text:
            print(
                f"{CORE_EXPECTED_PATH}: differs from the freshly computed values. Re-run without "
                "--check only if the corpus changed on purpose; otherwise the core hasher or "
                "signer regressed.",
                file=sys.stderr,
            )
            return 1
        print(f"{CORE_EXPECTED_PATH}: up to date ({len(document['placeholder_values'])} frozen values)")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(f"wrote {CORE_EXPECTED_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))